
stages:
  - prebuild
  - containers
  - builds
  - docs

.container_job_template: &container_job_definition
  image: docker:stable
  stage: containers
  needs: []
  services:
    - docker:dind
  before_script:
    - export TAG="$CI_REGISTRY_IMAGE/ci-$NAME:latest"
    - export COMMON_TAG="$CI_REGISTRY/libvirt/libvirt-python/ci-$NAME:latest"
    - docker info
    - docker login registry.gitlab.com -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker pull "$TAG" || docker pull "$COMMON_TAG" || true
    - docker build --cache-from "$TAG" --cache-from "$COMMON_TAG" --tag "$TAG" -f "ci/containers/ci-$NAME.Dockerfile" ci/containers
    - docker push "$TAG"
  after_script:
    - docker logout

.git_build_job_template: &git_build_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: builds
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LIBDIR="$VROOT/lib"
    - export LD_LIBRARY_PATH="$LIBDIR"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
    - export CFLAGS="-Werror"
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - $PYTHON setup.py build
    - $PYTHON setup.py install
    - $PYTHON setup.py test
    - $PYTHON setup.py sdist
    - if test -x /usr/bin/rpmbuild && test "$RPM" != "skip" ; then rpmbuild --nodeps -ta dist/libvirt-python*tar.gz ; fi

.dist_build_job_template: &dist_build_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: builds
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export CFLAGS="-Werror"
  script:
    - $PYTHON setup.py build
    - $PYTHON setup.py install
    - $PYTHON setup.py test
    - $PYTHON setup.py sdist
    - if test -x /usr/bin/rpmbuild && test "$RPM" != "skip" ; then rpmbuild --nodeps -ta dist/libvirt-python*tar.gz ; fi

# Check that all commits are signed-off for the DCO.
# Skip on "libvirt" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  stage: prebuild
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'

centos-7-container:
  <<: *container_job_definition
  variables:
    NAME: centos-7

centos-8-container:
  <<: *container_job_definition
  variables:
    NAME: centos-8

centos-stream-container:
  <<: *container_job_definition
  variables:
    NAME: centos-stream

debian-10-container:
  <<: *container_job_definition
  variables:
    NAME: debian-10

debian-sid-container:
  <<: *container_job_definition
  variables:
    NAME: debian-sid

fedora-32-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-32

fedora-33-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-33

fedora-rawhide-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-rawhide

opensuse-152-container:
  <<: *container_job_definition
  variables:
    NAME: opensuse-152
    RPM: skip

ubuntu-1804-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-1804

ubuntu-2004-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-2004


centos-8-git-build:
  <<: *git_build_job_definition
  needs:
    - centos-8-container
  variables:
    NAME: centos-8


centos-7-dist-build:
  <<: *dist_build_job_definition
  needs:
    - centos-7-container
  variables:
    NAME: centos-7

centos-8-dist-build:
  <<: *dist_build_job_definition
  needs:
    - centos-8-container
  variables:
    NAME: centos-8

centos-stream-dist-build:
  <<: *dist_build_job_definition
  needs:
    - centos-stream-container
  variables:
    NAME: centos-stream

debian-10-dist-build:
  <<: *dist_build_job_definition
  needs:
    - debian-10-container
  variables:
    NAME: debian-10

debian-sid-dist-build:
  <<: *dist_build_job_definition
  needs:
    - debian-sid-container
  variables:
    NAME: debian-sid

fedora-32-dist-build:
  <<: *dist_build_job_definition
  needs:
    - fedora-32-container
  variables:
    NAME: fedora-32

fedora-33-dist-build:
  <<: *dist_build_job_definition
  needs:
    - fedora-33-container
  variables:
    NAME: fedora-33

fedora-rawhide-dist-build:
  <<: *dist_build_job_definition
  needs:
    - fedora-rawhide-container
  variables:
    NAME: fedora-rawhide

opensuse-152-dist-build:
  <<: *dist_build_job_definition
  needs:
    - opensuse-152-container
  variables:
    NAME: opensuse-152
    RPM: skip

ubuntu-1804-dist-build:
  <<: *dist_build_job_definition
  needs:
    - ubuntu-1804-container
  variables:
    NAME: ubuntu-1804

ubuntu-2004-dist-build:
  <<: *dist_build_job_definition
  needs:
    - ubuntu-2004-container
  variables:
    NAME: ubuntu-2004
